Updated release.yaml
Signed-off-by: antublue <antublue@antublue.org>

diff --git a/release.yaml b/release.yaml
--- a/release.yaml
+++ b/release.yaml
@@ -5,7 +5,7 @@ pipeline:
       enabled: true
       steps:
         - name: check for release property
-          run: if [ -z "${{ release }}" ]; then echo "release property is required, exiting" && exit 1; fi
+          run: if [ -z "${{ release }}" ]; then echo "release variable is required, exiting" && exit 1; fi
         - name: check for ~/.m2/prometheus.settings.xml
           run: if [ -f "~/.m2/verifyica.settings.xml" ]; then echo "~/.m2/verifyica.settings.xml required, exiting" && exit 1; fi
         - name: change version
